DROP TABLE IF EXISTS COORDINATES;

CREATE TABLE COORDINATES (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	LON DOUBLE PRECISION NOT NULL,
	LAT DOUBLE PRECISION NOT NULL,
	CLIENTDATE TIMESTAMP NOT NULL,
	SERVERDATE TIMESTAMP NOT NULL
);

